version: '3.8'

networks:
  proxy-tier:
    name: proxy-tier

services:
  codeserver-python:
    image: ghcr.io/sgama/codeserver-python:latest
    container_name: codeserver-python
    expose:
      - 8080
    ports:
      - 8080:8080
    networks:
      - proxy-tier
    restart: always
    user:
      1000:1000
    volumes:
      # - .config:/home/coder/.config
      - vscode_data:/home/coder/project:rw

volumes:
  vscode_data:
    driver: local
    name: vscode_data
