name: Cross-compile
on:
  push:
    branches:
      - master

jobs: 
  native_build:
    name: Build ${{ matrix.distro }} ${{ matrix.arch }} on ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - arch: x86
            distro: ubuntu20.04
            os: ubuntu-20.04
          - arch: aarch64
            distro: ubuntu20.04
            os: ubuntu-20.04
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
